/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package electric_grid;
import io.dropwizard.Application;
import io.dropwizard.setup.Bootstrap;
import io.dropwizard.setup.Environment;

import electric_grid.resources.AppResource;
import electric_grid.health.AppHealthCheck;

public class App extends Application<AppConfiguration>{
    public static void main(String[] args) throws Exception {
        new App().run(args);
    }

    @Override
    public String getName() {
        return "hello-world";
    }

    @Override
    public void initialize(Bootstrap<AppConfiguration> bootstrap) {
        // Nothing to do yet
    }

    @Override
    public void run(AppConfiguration configuration,
                    Environment environment) {
        final AppResource resource = new AppResource(
                configuration.getTemplate(),
                configuration.getDefaultName()
        );
        final AppHealthCheck healthCheck =
                new AppHealthCheck(configuration.getTemplate());
        environment.healthChecks().register("template", healthCheck);
        environment.jersey().register(resource);
    }
}
